# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api_pb2 as api__pb2


class ImageScalerStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ScaleImage = channel.unary_unary(
        '/imagescaler.ImageScaler/ScaleImage',
        request_serializer=api__pb2.ScaleImageRequest.SerializeToString,
        response_deserializer=api__pb2.ScaleImageReply.FromString,
        )
    self.ScaleImageStream = channel.stream_stream(
        '/imagescaler.ImageScaler/ScaleImageStream',
        request_serializer=api__pb2.ScaleImageRequest.SerializeToString,
        response_deserializer=api__pb2.ScaleImageReply.FromString,
        )


class ImageScalerServicer(object):
  """Interface exported by the server.
  """

  def ScaleImage(self, request, context):
    """Obtain re-scaled and possibly grey scaled images
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ScaleImageStream(self, request_iterator, context):
    """Obtain re-scaled and possible grey scaled images
    as a stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageScalerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ScaleImage': grpc.unary_unary_rpc_method_handler(
          servicer.ScaleImage,
          request_deserializer=api__pb2.ScaleImageRequest.FromString,
          response_serializer=api__pb2.ScaleImageReply.SerializeToString,
      ),
      'ScaleImageStream': grpc.stream_stream_rpc_method_handler(
          servicer.ScaleImageStream,
          request_deserializer=api__pb2.ScaleImageRequest.FromString,
          response_serializer=api__pb2.ScaleImageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'imagescaler.ImageScaler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
